"""Add safety_events table

Revision ID: 0cc76ffd692a
Revises: 56f66a71b5c7
Create Date: 2026-02-20 03:47:13.441276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc76ffd692a'
down_revision: Union[str, Sequence[str], None] = '56f66a71b5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_created_at'), 'safety_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_safety_events_event_type'), 'safety_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_safety_events_session_id'), 'safety_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_events_session_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_event_type'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_created_at'), table_name='safety_events')
    op.drop_table('safety_events')
    # ### end Alembic commands ###
