"""Add language_original to chat_messages

Revision ID: 6626431dcda7
Revises: 0cc76ffd692a
Create Date: 2026-02-20 03:54:33.232258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6626431dcda7'
down_revision: Union[str, Sequence[str], None] = '0cc76ffd692a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('language_original', sa.String(), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'language_original')
    # ### end Alembic commands ###
