"""Add Assessment and AssessmentAnswer models

Revision ID: da72c1d6e145
Revises: 4659c952b923
Create Date: 2026-02-20 03:29:05.956122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da72c1d6e145'
down_revision: Union[str, Sequence[str], None] = '4659c952b923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('flags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_session_id'), 'assessments', ['session_id'], unique=False)
    op.create_index(op.f('ix_assessments_tool'), 'assessments', ['tool'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_assessments_tool'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_session_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
