"""Add sentiment_events table

Revision ID: ef723c9f87b3
Revises: 6626431dcda7
Create Date: 2026-02-20 03:59:35.153116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef723c9f87b3'
down_revision: Union[str, Sequence[str], None] = '6626431dcda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_events_created_at'), 'sentiment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_events_label'), 'sentiment_events', ['label'], unique=False)
    op.create_index(op.f('ix_sentiment_events_message_id'), 'sentiment_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_sentiment_events_session_id'), 'sentiment_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_events_session_id'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_message_id'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_label'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_created_at'), table_name='sentiment_events')
    op.drop_table('sentiment_events')
    # ### end Alembic commands ###
